<?xml version="1.0" encoding="utf-8"?><Database Name="employee" Class="EmployeeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-KARTIK\SQLEXPRESS;Initial Catalog=employee;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="linqsql.Properties.Settings" SettingsPropertyName="employeeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EmployeeDetails" Member="EmployeeDetails">
    <Type Name="EmployeeDetail">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeName" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="salary" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.InsertEmployee" Method="InsertEmployee">
    <Parameter Name="Empid" Parameter="empid" Type="System.Int32" DbType="Int" />
    <Parameter Name="EmpName" Parameter="empName" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="salary" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteEmployee" Method="DeleteEmployee">
    <Parameter Name="Empid" Parameter="empid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateEmployee" Method="UpdateEmployee">
    <Parameter Name="Empid" Parameter="empid" Type="System.Int32" DbType="Int" />
    <Parameter Name="EmpName" Parameter="empName" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="salary" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GETDETAILS" Method="GETDETAILS">
    <Parameter Name="empid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GETDETAILSResult">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeName" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="salary" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>